### ISSUE TITLE
meta: how can we support `eslint-define-config` better?

### ISSUE THREAD

**Issue by JounQin** [mdx-js/eslint-mdx#526]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

mdx support was added at https://github.com/eslint-types/eslint-define-config/pull/124, but somehow it's removed later?

I hope the end users can use `eslint-plugin-mdx` with typings support easily.

cc @Shinigami92

### Solution

I'm not quite familiar with `eslint-define-config`, so I'd prefer to listening from experienced @Shinigami92

### Alternatives

N/A

**Comment by Shinigami92** [comment]
There needs to be a file that can be imported via ref like `/// <reference types="eslint-plugin-mdx/define-config-support" />`

In that file it should look like e.g. https://github.com/eslint-types/define-config-plugin-types/blob/main/types/import/index.d.ts

**Comment by Shinigami92** [comment]
> Can that be supported from `eslint-plugin-mdx`'s side natively?

YES, thats why these global augmentations are there.

**Comment by JounQin** [comment]
Would you to raise a PR here? I'd to get some experiences here and then use it on `eslint-pligin-i` later. ❤️

**Comment by Shinigami92** [comment]
> Would you to raise a PR here? I'd to get some experiences here and then use it on `eslint-pligin-i` later. ❤️

Yeah, I can try 👍 
Not sure when, but I will try to set it on my list for this week

**Comment by JounQin** [comment]
It's not in emergency.

**Comment by JounQin** [comment]
https://github.com/eslint-types/eslint-define-config is deprecated.

**Comment by Shinigami92** [comment]
Do you want to open a new issue to add support for eslint's native `defineConfig`?

**Comment by JounQin** [comment]
> Maybe we could even define a pattern like defineMdxRules(...).

Does other plugins have similar concept?

**Comment by Shinigami92** [comment]
> Does other plugins have similar concept?

Nope 🥲
That's what I'm indirectly talking about

**Comment by JounQin** [comment]
I thought `eslint-define-config` aimed resolving this issue, but why it's archived if you still want that support then?

**Comment by Shinigami92** [comment]
eslint ships its own defineConfig now, and I don't want to infer with it, but want to let the community Switch to the native one!
The native solution is not so fully Ts strict than my solution was, and now I want to activate the community somehow to think about good DX for rule option types / autocompleting

**Comment by JounQin** [comment]
I agree missing `rule`/`settings` detail type info is disappointing, maybe it should be resolved in `defineConfig` from `eslint/config`, of `typescript-eslint`, for example, https://github.com/un-ts/eslint-plugin-import-x provides all necessary types https://app.unpkg.com/eslint-plugin-import-x@4.10.0/files/lib/index.d.ts that `typescript-eslint` can consume.
